apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-azurefile
  namespace: monitoramento 
spec:
  accessModes:
  - ReadWriteMany #- azure|aws
  #- ReadWriteOnce
  storageClassName: scw-bssd-retain #azurefile-strg
  resources:
    requests:
      storage: 5Gi